### ISSUE TITLE
Remove credentials from git repo and automate pulling of the repo to cloud nodes

### ISSUE THREAD

**Issue by birkland** [cornell-comp-internal/CloudLaunch#26]
This should greatly alleviate the need to build a new
image every time testing is needed, and as Adam pointed out, allow
users to easily customize the settings to their needs. May not do
before SC14.

Depends on: #10, #21, #36 

Edit: **Need to filter wiki repo as well**

**Comment by bbarker** [comment]
Now that the repo is open, it seems that you may need to delete a forked repo and refork if you want the fork status to show (which I assume is necessary for pull requests).

Also a good idea to delete a forked repo to remove the possibility of any credentials surfacing later.

**Comment by bbarker** [comment]
Last fix for this issue in #37
