### ISSUE TITLE
Compare image volumes for images emi-e1b610b6 (head-4) and emi-2b1442c7 (head-6)

### ISSUE THREAD

**Issue by birkland** [cornell-comp-internal/CloudLaunch#27]
It is not clear why cloud-init is not working on head-4.
See http://serverfault.com/questions/39534/best-way-to-compare-diff-a-full-directory-structure
for possible comparison tools.

**Comment by bbarker** [comment]
This is a pretty old issue at this juncture, so I'm closing it. Some mysteries are best left unresolved.
